"""empty message

Revision ID: 196cf26153ae
Revises: 98cd1b01c7f2
Create Date: 2022-11-16 10:17:35.700646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196cf26153ae'
down_revision = '98cd1b01c7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('skin_color', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('birth_year', sa.String(length=120), nullable=True),
    sa.Column('eye_color', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
